services:
  - type: web
    name: adai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    region: frankfurt
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: BOT_USERNAME
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: REMOVEBG_API_KEY
        sync: false
      - key: OWNER_ID
        sync: false
      - key: ADMIN_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: BASE_URL
        sync: false
      - key: WEBAPP_URL
        sync: false
      - key: FB_APP_ID
        sync: false
      - key: FB_APP_SECRET
        sync: false
      - key: PORT
        value: "8000"
